sudo: required
services:
  - docker

before_install:
  - docker build -t seenark/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true seenark/react-test npm test
  ## "-e CI=true" this mean when run test completed whether success or fail docker will not launching any watcher

after_sucess:
  ## build all image keep ready for push to Docker hub
  - docker build -t hadesgod/multi-client ./client
  - docker build -t hadesgod/multi-nginx ./nginx
  - docker build -t hadesgod/multi-server ./server
  - docker build -t hadesgod/multi-worker ./worker

  # log in to docker CLI but we didn't store username and password here we will store in travis environment variable secret
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take those images to docker hub
  - docker push hadesgod/multi-client
  - docker push hadesgod/multi-nginx
  - docker push hadesgod/multi-server
  - docker push hadesgod/multi-worker
